### ISSUE TITLE
Add blessing/bane when rolling a d20 + d4 simultaneously

### ISSUE THREAD

**Issue by carrierfry** [carrierfry/pixels-dndbeyond-userscript#12]

**Comment by carrierfry** [comment]
Maybe add a dropdown menu in the pixels info box to select an additional modifier for that

**Comment by carrierfry** [comment]
This has been implemented with version `1.0.0.0`

**Comment by HaarisQureshi** [comment]
Thank you for doing this!!! Has definitely been useful for certain rolls! 

I know this was implemented as a method where one would roll a d4 first then add the result as a mod, which is does do, but would it please be possible to re-open this as a stretch goal enhancement where it would enable it to be so, if you indicate you are rolling with bless/blane, the extension expects a d20 AND a d4 roll (I don't know if it accepts mixed dice rolls at the moment, as I don't yet have received my dice sets, I only have my d20, but I know it accepts multiples of the same die type - does it accept multiple dice types in a single roll?) and once you roll that it will do it in one go? You can indicate you are rolling a bless/bane roll either via a button on the overlay or - DnDBeyond now has an 'Effects' drop down in the extensions setting that toggles this on. So for example, either by pressing on a button or via DnDBeyond, I indicate I'm going to roll a bless, and then I press my attack roll button to send 1d20+9, and the Pixels extension prompts me to roll a 1x d20 and a 1x d4 and then adds the [d20] + [d4] + 9. 

As an additional stretch goal - a way to be more custom with this? For example if you wanted to roll a Bardic Inspiration dice or some features like Crimson Rite allow additional damage, I realise this would be more difficult, maybe a pop-out setting that lists all dice types and a drop down to allow you to select how many of each type you are planning to also roll? For example - I have a feat that means I am going to roll +1d6 damage, so I expand that setting and next to d4 I change it from 0 to 1, then I press the damage button next to my weapon, it sends the 1d10+5 to the extension, which subsequently prompts me to roll 1xd10 and 1xd6 if I have them connected, and then once I do it adds the [d10] + [d6] + 5? 

Thank you for considering - even if it's not something that can be implemented soon, I'd still be grateful if it's considered as a low prio enhancement for a later time! Thanks!
